name: University Touring Network
favicon: null
layout_spectrum: 0.50659
typography_spectrum: 1
title: University Touring Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-51468121-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e2dd'
    - '#56524f'
    - '#373330'
    - '#888481'
    - '#bdb6b1'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
